name: Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Vultr VM via SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.VULTR_HOST }}
          username: root
          password: ${{ secrets.VULTR_PASSWORD }}
          port: 22
          script: |
            cd hackathon-int20h
            git pull origin main
            docker exec laravel_app php artisan migrate --force
            docker exec laravel_app npm install
            docker exec laravel_app npm run build
