name: Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Vultr VM via SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.VULTR_HOST }}
          username: root
          password: ${{ secrets.VULTR_PASSWORD }}
          port: 22
          script: |
            cd hackathon-int20h
            git pull origin main
            alias sail='[ -f sail ] && sh sail || sh vendor/bin/sail'
            docker compose down
            docker compose up -d
            docker exec -it backend php artisan migrate --force
            docker exec -it backend npm run build
